provider "aws" {
  profile = "default"
  region  = "us-west-2"
}

resource "aws_s3_bucket" "origin-bucket" {
    bucket = "lab8-rt"
    acl = "public-read"

    tags = {
      Name = "lab8-rt"
    }
}

resource "aws_s3_bucket" "resized_bucket" {
    bucket = "lab8-rt-resized"
    acl = "public-read"
    tags = {
      Name = "lab8-rt-resized"
    }
}

resource "aws_iam_policy" "policy" {
  name = "rt_policy"
  path = "/"
  description = "autogenerated policy for lab 8"
  policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:PutLogEvents",
                "logs:CreateLogGroup",
                "logs:CreateLogStream"
            ],
            "Resource": "arn:aws:logs:*:*:*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject"
            ],
            "Resource": "arn:aws:s3:::lab8-rt/*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject"
            ],
            "Resource": "arn:aws:s3:::lab8-rt-resized/*"
        }
    ]
}
  EOF
}

resource "aws_iam_role" "role" {
  name = "rt_role"
  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Effect": "Allow"
    },
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
  EOF
}

resource "aws_iam_role_policy_attachment" "name" {
  role = aws_iam_role.role.name
  policy_arn = aws_iam_policy.policy.arn
}

resource "aws_lambda_function" "lambda" {
  function_name = "lab8lambda"
  role = aws_iam_role.role.arn
  handler = "index.handler"
  timeout = 10
  memory_size = 1024

  filename = "function.zip"
  source_code_hash = filebase64sha256("function.zip")

  runtime = "nodejs12.x"
}

resource "aws_lambda_permission" "bucket_permission" {
  statement_id = "AllowExecutionFromS3Bucket"
  action = "lambda:InvokeFunction"
  function_name = aws_lambda_function.lambda.arn
  principal = "s3.amazonaws.com"
  source_arn = aws_s3_bucket.origin-bucket.arn
}

resource "aws_s3_bucket_notification" "name" {
  bucket = aws_s3_bucket.origin-bucket.id
  lambda_function {
    lambda_function_arn = aws_lambda_function.lambda.arn
    events = ["s3:ObjectCreated:*"]
  }

  depends_on = [ aws_lambda_permission.bucket_permission ]
}
